import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

// DEV-ONLY generator (not part of the build). Extracts the shippable kanji->verb
// classification from the POC corpus: verb bucket + anonymized cluster id +
// stroke count ONLY. Heisig keywords/stories are deliberately NOT emitted — the
// game gets keywords at runtime from the host's session (jiten's own DB).
const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(__dirname, "../../../rtk-game/web/src/rtk/corpus-data.json");
const OUT = resolve(__dirname, "../src/rtk/kanji-verbs.ts");

interface RawEntry {
  kanji: string;
  verb: string;
  strokes: number;
  cluster?: string;
}
const raw = JSON.parse(readFileSync(SRC, "utf8")) as { entries: RawEntry[] };

// Map real cluster names -> opaque ids (c0, c1, ...) in first-seen order so no
// primitive keyword ever ships; the id is only used internally for grouping.
const clusterId = new Map<string, string>();
const anon = (name: string): string => {
  let id = clusterId.get(name);
  if (!id) {
    id = `c${clusterId.size}`;
    clusterId.set(name, id);
  }
  return id;
};

const lines = raw.entries.map((e) => {
  const parts = [`verb: "${e.verb}"`];
  if (e.cluster) parts.push(`cluster: "${anon(e.cluster)}"`);
  parts.push(`strokes: ${e.strokes}`);
  return `  "${e.kanji}": { ${parts.join(", ")} },`;
});

const body = `import type { VerbId } from "./verbs";

// AUTO-GENERATED by scripts/gen-kanji-verbs.ts — do not edit by hand.
// Shippable kanji classification: verb bucket + opaque cluster id + stroke count.
// Contains NO keywords or stories; those arrive per-session from the host.
export interface KanjiVerbInfo {
  verb: VerbId;
  cluster?: string;
  strokes: number;
}

export const KANJI_VERBS: Record<string, KanjiVerbInfo> = {
${lines.join("\n")}
};
`;

writeFileSync(OUT, body);
console.log(`wrote ${OUT}: ${raw.entries.length} kanji, ${clusterId.size} clusters`);
