import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import prettier from "eslint-plugin-prettier/recommended";

export default tseslint.config(
  {
    ignores: [
      "node_modules/",
      ".expo/",
      "dist/",
      "android/",
      "ios/",
      "babel.config.js",
      "metro.config.js",
      "tailwind.config.js",
      // Generated build artifacts (regenerated by build:reader / build:preprocessing)
      "packages/reader-webview/bundle.ts",
      "lib/share-extension/preprocessing.js",
      "expo-env.d.ts",
    ],
  },
  ...tseslint.configs.recommended,
  {
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },
  prettier,
  {
    rules: {
      // Enforce polymorphic confirm() instead of Alert.alert with callbacks
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "react-native",
              importNames: ["Alert"],
              message:
                "Use confirm() from @/lib/confirm instead of Alert.alert. Alert.alert callbacks don't work on web.",
            },
          ],
        },
      ],
      // Downgrade newer react-hooks rules to warn (fix incrementally)
      "react-hooks/immutability": "warn",
      "react-hooks/set-state-in-effect": "warn",
      // Relax rules that conflict with the codebase style
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  // Allow Alert import in the polymorphic wrapper itself
  {
    files: ["lib/confirm.native.ts"],
    rules: {
      "no-restricted-imports": "off",
    },
  },
);
