import type { KanjiEntry } from "./corpus";

// A small ORIGINAL stand-in corpus so the game boots and is playable during the
// embed phase. It intentionally does NOT ship the Heisig/Koohii-grounded data.
// Phase 2 replaces corpus consumption entirely with the host's session cards
// (real learned kanji) plus a shippable kanji->verb table. Covers all 16 verbs
// and provides three >=2-member clusters for the elite/boss "exact twin" ordeals.
export const STUB_ENTRIES: KanjiEntry[] = [
  {
    kanji: "火",
    keyword: "fire",
    verb: "burn",
    primitives: [],
    story: "",
    strokes: 4,
    cluster: "fire",
  },
  {
    kanji: "炎",
    keyword: "flame",
    verb: "burn",
    primitives: [{ keyword: "fire" }],
    story: "",
    strokes: 8,
    cluster: "fire",
  },
  {
    kanji: "灯",
    keyword: "lamp",
    verb: "reveal",
    primitives: [{ keyword: "fire" }],
    story: "",
    strokes: 6,
    cluster: "fire",
  },
  {
    kanji: "焼",
    keyword: "bake",
    verb: "harm",
    primitives: [{ keyword: "fire" }],
    story: "",
    strokes: 12,
    cluster: "fire",
  },
  {
    kanji: "水",
    keyword: "water",
    verb: "douse",
    primitives: [],
    story: "",
    strokes: 4,
    cluster: "water",
  },
  {
    kanji: "氷",
    keyword: "ice",
    verb: "stop",
    primitives: [{ keyword: "water" }],
    story: "",
    strokes: 5,
    cluster: "water",
  },
  {
    kanji: "泉",
    keyword: "spring",
    verb: "rise",
    primitives: [{ keyword: "water" }],
    story: "",
    strokes: 9,
    cluster: "water",
  },
  {
    kanji: "河",
    keyword: "river",
    verb: "rush",
    primitives: [{ keyword: "water" }],
    story: "",
    strokes: 8,
    cluster: "water",
  },
  {
    kanji: "木",
    keyword: "tree",
    verb: "grow",
    primitives: [],
    story: "",
    strokes: 4,
    cluster: "wood",
  },
  {
    kanji: "林",
    keyword: "grove",
    verb: "grow",
    primitives: [{ keyword: "tree" }],
    story: "",
    strokes: 8,
    cluster: "wood",
  },
  {
    kanji: "森",
    keyword: "forest",
    verb: "hide",
    primitives: [{ keyword: "tree" }],
    story: "",
    strokes: 12,
    cluster: "wood",
  },
  {
    kanji: "根",
    keyword: "root",
    verb: "block",
    primitives: [{ keyword: "tree" }],
    story: "",
    strokes: 10,
    cluster: "wood",
  },
  { kanji: "刀", keyword: "sword", verb: "cut", primitives: [], story: "", strokes: 2 },
  { kanji: "門", keyword: "gate", verb: "open", primitives: [], story: "", strokes: 8 },
  { kanji: "山", keyword: "mountain", verb: "strike", primitives: [], story: "", strokes: 3 },
  {
    kanji: "落",
    keyword: "fall",
    verb: "fall",
    primitives: [{ keyword: "flower" }, { keyword: "water" }],
    story: "",
    strokes: 12,
  },
  { kanji: "心", keyword: "heart", verb: "heal", primitives: [], story: "", strokes: 4 },
  {
    kanji: "花",
    keyword: "flower",
    verb: "charm",
    primitives: [{ keyword: "flower" }],
    story: "",
    strokes: 7,
  },
];
